# Generated by Django 4.2.30 on 2026-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gemini_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interview_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
