# Generated by Django 4.2.30 on 2026-08-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_resume_ats_score_resume_ats_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('skill_level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('roadmap', models.TextField()),
                ('roadmap_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='analyzer.resume')),
            ],
        ),
    ]
